---
stages:
  - validate
  - lint

validate:
  stage: validate
  image:
    name: "hashicorp/terraform:0.12.29"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
      - >-
        find . -type f -name "*.tf" -exec dirname {} \;
        | sort -u
        | while read line; do
            cd $line;
            echo "processing $PWD ..."
            terraform init -backend=false
            cd -;
          done

  script:
      - terraform --version
      -  echo "Terraform Init !"
      - terraform init
      - echo "Terraform Validate !"
      - terraform validate

  only: 
      - branches

  artifacts:
    paths:
      - .terraform

terralint:
  stage: lint
  image:
    name: "wata727/tflint"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - tflint  --config $CI_PROJECT_DIR/.tflint.hcl;
