---
stages:
  - validate
  - lint

validate:
  stage: validate
  image:
    name: "hashicorp/terraform:0.12.29"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
      - terraform --version
      - tflint -v
      - echo "Terraform Init !"
      - terraform init -input=false


  script:
      - echo "Terraform Validate !"
      - terraform validate

  artifacts:
    paths:
      - .terraform

terralint:
  stage: lint
  image:
    name: "wata727/tflint"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - tflint
