---
stages:
  - validate
  - lint

validate:
  stage: validate
  image:
    name: "hashicorp/terraform:0.12.8"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
      - rm -rf .terraform
      - terraform --version
      - terraform init
      - |
      #!/bin/sh
      fmt_diff=$(find . -name "*.tf" | xargs -I{} /terraform fmt -write=false {} | sed '/^\s*$/d')
      if test -n "$fmt_diff"; then
        echo "******* Terraform formatting error:"
        echo ""
        echo $fmt_diff
        exit 1
      fi


  script:
      - echo Validate ! 
      - terraform validate -check-variables=false
  artifacts:
    paths:
      - .terraform

terralint:
  stage: lint
  image:
    name: "wata727/tflint"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - tflint --error-with-issues
