---
stages:
  - validate
  - lint

validate:
  stage: validate
  image:
    name: "hashicorp/terraform:0.12.8"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
      - ./script.sh

  script:
      - echo "Terraform Init !"
      - terreform init
      - echo "Terraform Validate !"
      - terraform validate -check-variables=false
  artifacts:
    paths:
      - .terraform

terralint:
  stage: lint
  image:
    name: "wata727/tflint"
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - tflint --error-with-issues
